---
version: '2'

services:

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - /home/andrey_m/docker/14.Docker/docker-compose_1/path/to/movies:/movies
      - /home/andrey_m/docker/14.Docker/docker-compose_1/path/to/downloadclient-downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - /home/andrey_m/docker/14.Docker/docker-compose_1/path/to/tvseries:/tv
      - /home/andrey_m/docker/14.Docker/docker-compose_1/path/to/downloadclient-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
